version: "3"

services:
  dcm2bids:
    image: dcm2bids/pisiii
    volumes:
      - ./raw:/app
      - ./output:/output
      - ./custom/config.json:/config/config.json
      - ./custom/dataset_description.json:/config/dataset_description.json
      - ./custom/participants.tsv:/config/participants.tsv
      - ./custom/participants.json:/config/participants.json
  fsl: 
    image: fsl/pisiii
    volumes:
      - ./output:/output
      - ./custom/parameters.json:/config/parameters.json
      - ./custom/design.fsf:/config/design.fsf
    depends_on:
      - dcm2bids
networks:
  my_network:
    name: bids_and_fsl

