version: "3"


services:
  dcm2bids:
    build: 
        context: ./bids
        dockerfile: Dockerfile
    volumes:
      - ./raw:/app
      - ./output:/output
      - ./config.json:/config/config.json
      
  fsl: 
    build: 
      context: ./fsl
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
    depends_on:
      - dcm2bids  
    networks:
      - my_network


networks:
  my_network:

