FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    gnupg \
    software-properties-common \
    python3 \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*


RUN wget -O- https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py | python3 - -d /usr/local/fsl 

ENV FSLDIR=/usr/local/fsl
ENV PATH=${FSLDIR}/bin:$PATH
ENV LD_LIBRARY_PATH=${FSLDIR}/lib:$LD_LIBRARY_PATH

WORKDIR /app

COPY . /app


RUN mkdir /nifti && \ 
for folder in /app/*; do dcm2niix -o "$folder" "$folder"; \
mv "$folder"/*.nii /nifti; \ 
done 

RUN for file in /app/NIfTI/*/*.nii*; do \
        subfolder=$(basename "$(dirname "$file")"); \
        filename=$(basename "$file"); \
mkdir /app/brain && \
for file in /nifti/*.nii; do base=$(basename $file); bet $file /app/brain/${base%.nii}_brain -f 0.5 -g 0 -m; done && \
    mv /app/*/*_brain.nii.gz /data/; \
done

