FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    gnupg \
    software-properties-common \
    python3 \
    python3-pip && \
    apt-get install -y git build-essential cmake zlib1g-dev  &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/rordenlab/dcm2niix.git && \
    cd dcm2niix && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf dcm2niix

RUN wget -O- https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py | python3 - -d /usr/local/fsl 

ENV FSLDIR=/usr/local/fsl
ENV PATH=${FSLDIR}/bin:$PATH
ENV FSLOUTPUTTYPE=NIFTI_GZ
ENV LD_LIBRARY_PATH=${FSLDIR}/lib:$LD_LIBRARY_PATH


WORKDIR /app

COPY ./ST1 /app


RUN mkdir /nifti && \ 
for folder in /app/*; do dcm2niix -o "$folder" "$folder"; \
mv "$folder"/*.nii /nifti; \ 
done 

RUN for file in /app/NIfTI/*/*.nii*; do \
        subfolder=$(basename "$(dirname "$file")"); \
        filename=$(basename "$file"); \
        done

RUN mkdir /app/brain /output && \
    for file in /nifti/*.nii; do base=$(basename $file); \
    bet $file /app/brain/${base%.nii}_brain -f 0.5 -g 0 -m;done && \
    mv /app/brain/*_brain.nii.gz /output/ 
    
RUN cp -r /output /data/

VOLUME /output

CMD ["bash"]
