FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    gnupg \
    software-properties-common \
    python3 \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*


RUN wget -O- https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py | python3 - -d /usr/local/fsl 

ENV FSLDIR=/usr/local/fsl
ENV PATH=${FSLDIR}/bin:$PATH
ENV LD_LIBRARY_PATH=${FSLDIR}/lib:$LD_LIBRARY_PATH

WORKDIR /app


COPY requirements.txt /app
RUN pip3 install --no-cache-dir -r requirements.txt


COPY . /app

CMD ["python3", "app.py"]

