version: "3"

services:
  dcm2bids:
    image: pisiii_fsl-dcm2bids
    volumes:
      - ./raw:/app
      - ./output:/output
      - ./custom/config.json:/config/config.json
      - ./custom/dataset_description.json:/config/dataset_description.json
      - ./custom/participants.tsv:/config/participants.tsv
      - ./custom/participants.json:/config/participants.json
  fsl: 
    image: pisiii_fsl-fsl
    volumes:
      - ./output:/output
      - ./custom/parameters.json:/config/parameters.json
    depends_on:
      - dcm2bids
networks:
  my_network:
    name: bids_and_fsl

